stages:
  load_data:
    cmd: python src/load_data.py --config=params.yaml
    deps:
    - src/get_data.py
    - src/load_data.py
    - data_given/train_data.csv
    - data_given/test_data.csv
    outs:
    - data/raw/train.csv
    - data/raw/test.csv

  preprocess_and_split:
    cmd: python src/preprocess.py --config=params.yaml
    deps:
    - src/preprocess_and_split.py
    - prediction_service/preprocess_prediction.py
    - data/raw/train.csv
    - data/raw/test.csv
    outs:
    - data/processed/train_processed.csv
    - data/processed/test_processed.csv

  train_and_evaluate:
    cmd: python src/train_and_evaluate.py --config=params.yaml
    deps:
    - data/processed/train_processed.csv
    - data/processed/test_df.csv
    - src/train_and_evaluate.py
    params:
    - estimators.XGBoost.n_estimators
    - estimators.XGBoost.learning_rate
    - estimators.XGBoost.max_depth
  log_production_model:
    cmd: python src/log_production_model.py --config=params.yaml
    deps:
      - src/log_production_model.py