base:
  project: GA-MLOps
  target_col: TARGET

data_source:
  train_source: data_given/train.csv
  test_source: data_given/test.csv

load_data:
  raw_train_data_csv: data/raw/train.csv
  raw_test_data_csv: data/raw/test.csv

split_data:
  train_path: data/proecessed/train_processed.csv
  test_path: data/proecessed/test_processed.csv


estimators:
  XGBoost:
      n_estimators: 1000
      learning_rate: 0.5
      max_depth: 8

model_dir: saved_models

reports:
  params: report/params.json
  scores: report/scores.json

webapp_model_dir: prediction_service/model/xgb_model.pkl
webapp_model_dir_1: prediction_service/model/xgboost_model.pkl

mlflow_config:
  artifacts_dir: artifacts
  experiment_name: XG-Boost Regression
  run_name: mlops
  registered_model_name: XGBoostModel
  remote_server_uri: http://127.0.0.1:5000/
